apiVersion: v1
kind: Service
metadata:
  name: hospital-backend-svc
  namespace: hospital
  labels:
    app: hospital-backend
spec:
  type: LoadBalancer
  selector:
    app: hospital-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
